INSERT INTO CONTACT (FIRSTNAME, LASTNAME,BIRTHDATE) VALUES ('Smile', 'Lena','1988-03-13');
INSERT INTO CONTACT (FIRSTNAME, LASTNAME,BIRTHDATE) VALUES ('Smile', 'Alex','2010-10-31');
INSERT INTO CONTACT (FIRSTNAME, LASTNAME,BIRTHDATE) VALUES ('Oleksenko', 'Vika','1988-12-24');


INSERT INTO SECURITY (LOGIN, PASS) VALUES ('lena', '1111');
INSERT INTO SECURITY (LOGIN, PASS) VALUES ('alex', '1111');
INSERT INTO SECURITY (LOGIN, PASS) VALUES ('vika', '1111');

INSERT INTO FRIENDSHIP (ID, FRIEND_ID) VALUES ('1', '3');
INSERT INTO FRIENDSHIP (ID, FRIEND_ID) VALUES ('1', '2');
INSERT INTO FRIENDSHIP (ID, FRIEND_ID) VALUES ('2', '3');
INSERT INTO FRIENDSHIP (ID, FRIEND_ID) VALUES ('3', '1');
INSERT INTO FRIENDSHIP (ID, FRIEND_ID) VALUES ('2', '1');


INSERT INTO HOBBY (TITLE, DESCRIPTION) VALUES ('Travel', 'qwerty');
INSERT INTO HOBBY (TITLE, DESCRIPTION) VALUES ('Dancing', 'qwerty');
INSERT INTO HOBBY (TITLE, DESCRIPTION) VALUES ('Dance', 'qwerty');
INSERT INTO HOBBY (TITLE, DESCRIPTION) VALUES ('Write books', 'qwerty');
INSERT INTO HOBBY (TITLE, DESCRIPTION) VALUES ('Sport', 'qwerty');

INSERT INTO HOBBES_CONTACT (CONTACT_ID, HOBBES_ID) VALUES ('1', '1');
INSERT INTO HOBBES_CONTACT (CONTACT_ID, HOBBES_ID) VALUES ('2', '4');
INSERT INTO HOBBES_CONTACT (CONTACT_ID, HOBBES_ID) VALUES ('1', '3');
INSERT INTO HOBBES_CONTACT (CONTACT_ID, HOBBES_ID) VALUES ('3', '2');
INSERT INTO HOBBES_CONTACT (CONTACT_ID, HOBBES_ID) VALUES ('3', '3');
INSERT INTO HOBBES_CONTACT (CONTACT_ID, HOBBES_ID) VALUES ('2', '1');
INSERT INTO HOBBES_CONTACT (CONTACT_ID, HOBBES_ID) VALUES ('1', '4');
INSERT INTO HOBBES_CONTACT (CONTACT_ID, HOBBES_ID) VALUES ('1', '5');


INSERT INTO PLACE (TITLE, DESCRIPTION) VALUES ('Paris', 'qwerty');
INSERT INTO PLACE (TITLE, DESCRIPTION) VALUES ('London', 'qwerty');
INSERT INTO PLACE (TITLE, DESCRIPTION) VALUES ('NewYork', 'qwerty');
INSERT INTO PLACE (TITLE, DESCRIPTION) VALUES ('Dnepropetrovsk', 'qwerty');
INSERT INTO PLACE (TITLE, DESCRIPTION) VALUES ('Kuiv', 'qwerty');

INSERT INTO PLACES_CONTACT (CONTACT_ID, PLACES_ID) VALUES ('1', '1');
INSERT INTO PLACES_CONTACT (CONTACT_ID, PLACES_ID) VALUES ('2', '4');
INSERT INTO PLACES_CONTACT (CONTACT_ID, PLACES_ID) VALUES ('1', '3');
INSERT INTO PLACES_CONTACT (CONTACT_ID, PLACES_ID) VALUES ('3', '2');
INSERT INTO PLACES_CONTACT (CONTACT_ID, PLACES_ID) VALUES ('3', '3');
INSERT INTO PLACES_CONTACT (CONTACT_ID, PLACES_ID) VALUES ('2', '1');
INSERT INTO PLACES_CONTACT (CONTACT_ID, PLACES_ID) VALUES ('1', '4');
INSERT INTO PLACES_CONTACT (CONTACT_ID, PLACES_ID) VALUES ('1', '5');

INSERT INTO MASSEGE (IDCONTACT1, IDCONTACT2,MESSAGETEXT,DATE_MASSEGE) VALUES ('1', '3','mess1','2010-11-03');
INSERT INTO MASSEGE (IDCONTACT1, IDCONTACT2,MESSAGETEXT,DATE_MASSEGE) VALUES ('1', '2','mess2','2012-04-13');
INSERT INTO MASSEGE (IDCONTACT1, IDCONTACT2,MESSAGETEXT,DATE_MASSEGE) VALUES ('1', '3','mess3','2013-10-01');
INSERT INTO MASSEGE (IDCONTACT1, IDCONTACT2,MESSAGETEXT,DATE_MASSEGE) VALUES ('3', '2','mess4','2012-03-17');
INSERT INTO MASSEGE (IDCONTACT1, IDCONTACT2,MESSAGETEXT,DATE_MASSEGE) VALUES ('2', '3','mess5','2015-09-04');
INSERT INTO MASSEGE (IDCONTACT1, IDCONTACT2,MESSAGETEXT,DATE_MASSEGE) VALUES ('1', '2','mess6','2015-10-23');