DROP TABLE IF EXISTS CONTACT;
DROP TABLE IF EXISTS SECURITY;
DROP TABLE IF EXISTS PLACES_CONTACTT;
DROP TABLE IF EXISTS PLACES;
DROP TABLE IF EXISTS HOBBY_CONTACT;
DROP TABLE IF EXISTS HOBBY;
DROP TABLE IF EXISTS FRIENDSHIP;
DROP TABLE IF EXISTS MASSEGE;

CREATE TABLE CONTACT (
       ID INT NOT NULL AUTO_INCREMENT
     , FIRSTNAME VARCHAR(40) NOT NULL
     , LASTNAME VARCHAR(40) NOT NULL
     , BIRTHDATE DATE
     , PRIMARY KEY (ID)

);

CREATE TABLE SECURITY (
       SECURITY_ID INT NOT NULL AUTO_INCREMENT
     , PRIMARY KEY (SECURITY_ID)
     , LOGIN VARCHAR(16) NOT NULL
     , PASS VARCHAR(16) NOT NULL
     , CONSTRAINT FK_SECURITY FOREIGN KEY (SECURITY_ID)
                  REFERENCES CONTACT (ID) ON DELETE CASCADE

);




CREATE TABLE FRIENDSHIP (
       ID INT NOT NULL
     , FRIEND_ID INT NOT NULL
     , PRIMARY KEY (ID, FRIEND_ID)
     , CONSTRAINT FK_CONTACT FOREIGN KEY (ID)
                  REFERENCES CONTACT (ID) ON DELETE CASCADE
     , CONSTRAINT FK_FRIEND FOREIGN KEY (FRIEND_ID)
                  REFERENCES CONTACT (ID) ON DELETE CASCADE
);


CREATE TABLE HOBBY (
       HOBBY_ID INT NOT NULL AUTO_INCREMENT
     , DESCRIPTION VARCHAR(250) NOT NULL
     , TITLE VARCHAR(40) NOT NULL
     , PRIMARY KEY (HOBBY_ID)
);


CREATE TABLE HOBBES_CONTACT (
       CONTACT_ID INT NOT NULL
     , HOBBES_ID INT NOT NULL
     , PRIMARY KEY (CONTACT_ID, HOBBES_ID)
     , CONSTRAINT FK_HOBBES_CONTACT FOREIGN KEY (CONTACT_ID)
                  REFERENCES CONTACT (ID) ON DELETE CASCADE
     , CONSTRAINT FK_HOBBES FOREIGN KEY (HOBBES_ID)
                  REFERENCES HOBBY (HOBBY_ID) ON DELETE CASCADE
);


CREATE TABLE PLACE (
       PLACE_ID INT NOT NULL AUTO_INCREMENT
     , DESCRIPTION VARCHAR(250) NOT NULL
     , TITLE VARCHAR(40) NOT NULL
     , PRIMARY KEY (PLACE_ID)
);


CREATE TABLE PLACES_CONTACT (
       CONTACT_ID INT NOT NULL
     , PLACES_ID INT NOT NULL
     , PRIMARY KEY (CONTACT_ID, PLACES_ID)
     , CONSTRAINT FK_PLACES_CONTACT FOREIGN KEY (CONTACT_ID)
                  REFERENCES CONTACT (ID) ON DELETE CASCADE
     , CONSTRAINT FK_PLACES FOREIGN KEY (PLACES_ID)
                  REFERENCES PLACE (PLACE_ID) ON DELETE CASCADE
);


CREATE TABLE MASSEGE(

       MASSEGE_ID INT NOT NULL AUTO_INCREMENT
     , IDCONTACT1 INT(10000) NOT NULL
     , IDCONTACT2 INT(10000) NOT NULL
     , MESSAGETEXT VARCHAR(250) NOT NULL
     , DATE_MASSEGE DATETIME NOT NULL
     , PRIMARY KEY (MASSEGE_ID)

     , CONSTRAINT FK_CONTACT2 FOREIGN KEY (IDCONTACT2)
                  REFERENCES CONTACT (ID) ON DELETE CASCADE
);